---
# ==============================================================================
# Role: Webserver (PHP Runtime & KopDes Application on Alpine Linux)
# ==============================================================================

- name: Pasang runtime PHP dan ekstensi yang dibutuhkan di Alpine Linux
  ansible.builtin.package:
    name:
      - php
      - php-cli
      - php-pdo
      - php-pdo_mysql
      - php-pdo_sqlite
      - php-session
      - php-json
      - php-curl
      - php-openssl
      - php-mbstring
      - php-tokenizer
      - php-ctype
    state: present

- name: Pastikan direktori aplikasi dan log KopDes tersedia
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ app_dest_dir }}"
    - "/var/log/kopdes"

- name: Deploy direktori source code KopDes dari repository
  ansible.builtin.copy:
    src: "../{{ item }}"
    dest: "{{ app_dest_dir }}/"
    mode: '0755'
  loop:
    - config
    - database
    - includes
    - pages
    - public

- name: Inject file konfigurasi .env sesuai identitas node ({{ server_node_name }})
  ansible.builtin.template:
    src: env.j2
    dest: "{{ app_dest_dir }}/.env"
    mode: '0644'
  notify: Restart KopDesWeb

- name: Pasang skrip layanan OpenRC untuk web server KopDes
  ansible.builtin.template:
    src: kopdes.initd.j2
    dest: /etc/init.d/kopdes
    mode: '0755'
  notify: Restart KopDesWeb

- name: Pastikan layanan web server KopDes aktif dan berjalan saat booting
  ansible.builtin.service:
    name: kopdes
    state: started
    enabled: yes
