---
# ==============================================================================
# Role: Common (Baseline Alpine Linux Configuration for All 4 VMs)
# ==============================================================================

- name: Pastikan repositori apk terbaru dan Python 3 terpasang
  ansible.builtin.raw: apk update && apk add --no-cache python3 curl ca-certificates openrc
  changed_when: false

- name: Pastikan direktori log KopDes tersedia
  ansible.builtin.file:
    path: "/var/log/kopdes"
    state: directory
    mode: '0755'

