# ==============================================================================
# ANSIBLE INVENTORY: KOPDES LAB 4 TARGET VMS (ALPINE LINUX)
# ==============================================================================
# =====================================================
# WAJIB DIUBAH SISWA
# GANTI X (17) DENGAN NOMOR ABSEN ANDA
# =====================================================

[haproxy]
haproxy-node ansible_host=192.168.17.10

[webservers]
web01-node ansible_host=192.168.17.11 server_node_name=WEB-01
web02-node ansible_host=192.168.17.12 server_node_name=WEB-02

[database]
db01-node ansible_host=192.168.17.13

# =====================================================
# Grouping Seluruh VM Alpine Linux & Konfigurasi SSH
# =====================================================
[alpine:children]
haproxy
webservers
database

[alpine:vars]
ansible_user=root
ansible_password=root
ansible_connection=ssh
ansible_port=22
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
