# ==============================================================================
# ANSIBLE INVENTORY: KOPDES LAB 4 TARGET VMS (WINDOWS)
# ==============================================================================
# =====================================================
# WAJIB DIUBAH SISWA
# GANTI X (17) DENGAN NOMOR ABSEN ANDA
# =====================================================

[haproxy]
haproxy-node ansible_host=192.168.17.10

[webservers]
web01-node ansible_host=192.168.17.11 server_node_name=WEB-01
web02-node ansible_host=192.168.17.12 server_node_name=WEB-02

[database]
db01-node ansible_host=192.168.17.13

# =====================================================
# Grouping Seluruh VM Windows & Konfigurasi WinRM
# =====================================================
[windows:children]
haproxy
webservers
database

[windows:vars]
ansible_user=Administrator
ansible_password=PasswordKopdes2025!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_winrm_operation_timeout_sec=120
ansible_winrm_read_timeout_sec=150
